Repository jenkinsci/docker-ssh-agent, pull requests merged in 2019-12, with the labels that each got.

#38 Enable Release Drafter in the repository
  .github/release-drafter.yml
Labels: chore

#35 Added Java 8 Alpine packaging
  Dockerfile-alpine
  Makefile
  setup-sshd
  tests/keys.bash
  tests/test_helpers.bash
  tests/tests.bats
Labels: enhancement

#39 Add explicit MIT license to the repository
  LICENSE
Labels: documentation

#41 Move the JDK11 image to the master branch
  Dockerfile-jdk11
Labels: chore

#42 [JENKINS-60587] - Cleanup some "slave" references in README
  README.md
Labels: documentation

#44 Enable autotests for JDK11
  Makefile
  tests/tests.bats
Labels: chore

#43 #40 - Introduce version tags for the Docker image
  README.md
Labels: enhancement
