Repository jenkinsci/docker-ssh-agent, pull requests merged in 2020-04, with the labels that each got.

#49 Change the directory structure + Improve test coverage and uniform code
  .gitignore
  11/debian/Dockerfile
  11/nanoserver-1809/Dockerfile
  11/windowsservercore-1809/Dockerfile
  8/alpine/Dockerfile
  8/debian/Dockerfile
  8/nanoserver-1809/Dockerfile
  8/windowsservercore-1809/Dockerfile
  CreateProfile.psm1
  Jenkinsfile
  Makefile
  README.md
  make.ps1
  setup-sshd
  setup-sshd.ps1
  tests/libcrypto.dll
  tests/ssh.exe
  tests/sshAgent.Tests.ps1
  tests/test_helpers.bash
  tests/test_helpers.psm1
  tests/tests.bats
Labels: chore

#50 INFRA-1105 - Rename the image to jenkins/ssh-agent, stop building generic Windows tags
  README.md
  make.ps1
Labels: chore, documentation, enhancement

#51 Add Gitter chat link to README
  README.md
Labels: documentation

#52 Remove the "v" prefix from release tags
  .github/release-drafter.yml
Labels: chore

#53 README: Replace DockerHub stars badge by GitHub ones
  README.md
Labels: documentation
