Repository jenkinsci/docker-ssh-agent, pull requests merged in 2022-05, with the labels that each got.

#121 chore(alpine-jdk8) cleanup Dockerfile
  8/alpine/Dockerfile
Labels: chore

#126 fix(bullseye) ensure that locale is correctly set to C.UTF-8 for all cases
  11/bullseye/Dockerfile
  17/bullseye/Dockerfile
  8/alpine/Dockerfile
  8/bullseye/Dockerfile
  Makefile
  tests/test_helpers.bash
  tests/tests.bats
Labels: bug

#123 feat: introduces a new alpine-jdk17 image based on eclipse-temurin:17.0.2_8-jdk-alpine
  17/alpine/Dockerfile
  docker-bake.hcl
Labels: enhancement

#122 feat: introduces a new alpine-jdk11 image based on eclipse-temurin:11.0.14.1_1-jdk-alpine
  .github/dependabot.yml
  11/alpine/Dockerfile
  docker-bake.hcl
Labels: enhancement

#128 jenkins/ssh-agent:alpine looking for Java in wrong place
  11/alpine/Dockerfile
  17/alpine/Dockerfile
  8/alpine/Dockerfile
  tests/tests.bats
Labels: bug
