Repository jenkinsci/docker-ssh-agent, pull requests merged in 2022-11, with the labels that each got.

#178 chore(github-actions) cleanup workflows to only have 1 release-drafter generation
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/release-drafter.yml
Labels: chore

#179 chore(linux) Add a test to ensure that git and the SSH client are installed
  11/alpine/Dockerfile
  11/bullseye/Dockerfile
  17/alpine/Dockerfile
  17/bullseye/Dockerfile
  8/alpine/Dockerfile
  8/bullseye/Dockerfile
  tests/tests.bats
Labels: chore

#180 chore(release-drafter) Allow manual trigger of the release drafter workflow to update changelogs
  .github/workflows/release-drafter.yml
Labels: chore

#181 chore(linux) Add `less` and `patch` packages explicitly and a test to validate the installation
  11/alpine/Dockerfile
  11/bullseye/Dockerfile
  17/alpine/Dockerfile
  17/bullseye/Dockerfile
  8/alpine/Dockerfile
  8/bullseye/Dockerfile
  tests/tests.bats
Labels: enhancement

#184 fix(docker) Change the permissions on the newly declared volumes
  11/alpine/Dockerfile
  11/bullseye/Dockerfile
  17/alpine/Dockerfile
  17/bullseye/Dockerfile
  8/alpine/Dockerfile
  8/bullseye/Dockerfile
  tests/tests.bats
Labels: bug

#185 chore(test) Uses `"${AGENT_WORKDIR}"` instead of hardcoded path.
  tests/tests.bats
Labels: chore

#188 Note that `-p` is also necessary
  README.md
Labels: documentation

#189 feat(documentation) Adding information on how to build the images locally
  README.md
Labels: documentation
